Web/Controllers/CardController.cs
using Domain.Abstract;
using Domain.Context;
using Domain.Organization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class CardController : Controller
    {
        private AccessoriesDbContext db = new AccessoriesDbContext();
        private IAccessory repository;
        private IOrder order;
        public CardController(IAccessory repo, IOrder ord)
        {
            repository = repo;
            order = ord;
        }

        public ViewResult Index(Card card, string returnUrl)
        {
            return View(new CardToBye
            {
                Card = card,
                ReturnUrl = returnUrl
            });
        }

        //Add Items to card (basket)
        public RedirectToRouteResult AddToCard(Card card, int accessoryId, string returnUrl)
        {
            Accessory accessory = repository.Accessories.FirstOrDefault(g => g.AccessoryId == accessoryId);

            if (accessory != null)
            {
                card.Add(accessory, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //Delete Items to card (basket)
        public RedirectToRouteResult RemoveFromCart(Card card, int accessoryId, string returnUrl)
        {
            Accessory accessory = repository.Accessories.FirstOrDefault(g => g.AccessoryId == accessoryId);

            if (accessory != null)
            {
                card.Remove(accessory);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Card card)
        {
            return PartialView(card);
        }

        //Order Items with card (basket)
        public ViewResult Order()
        {
            return View(new Shiping());
        }

        [HttpPost]
        public ViewResult Order(Card card, Shiping shiping)
        {
            if(card.Cards.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your card is empty");
            }
            if(ModelState.IsValid)
            {
                order.ProcessOrder(card, shiping);
                card.Delite();
                return View("Completed");
            }
            else
            {
                return View(shiping);
            }
        }

        //Search concrete item. Don't work
        [HttpPost]
        public ActionResult Search(string name)
        {
            var accessories = db.Accessories.Where(t => t.Name.Contains(name)).ToList();
            if (accessories.Count <= 0)
            {
                return HttpNotFound();
            }
            return PartialView(accessories);
        }
    }
}

Web/Controllers/MenuNavigationController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class MenuNavigationController : Controller
    {
        private IAccessory repository;

        public MenuNavigationController(IAccessory repo)
        {
            repository = repo;
        }

        // Menu Navigation for Main List
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> cat = repository.Accessories
                .Select(a => a.Cathegory)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(cat);
        }
    }
}

Web/Views/Shared/Summary.cshtml
@model Domain.Organization.Accessory

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Cost.ToString("# $")</span>
    </h3>

    @using (Html.BeginForm("AddToCard", "Card"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.AccessoryId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to Card" />
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

Web/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/Errors.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Accessories Store - Gadgets and Electronics</a>
        @Html.Action("Summary", "Card")
    </div>
    <div class="row panel">
        <div id="categories" class="col-md-3">
            @Html.Action("Menu", "MenuNavigation")
        </div>
        <div class="col-md-8">
            @RenderBody()
        </div>
    </div>

</body>
</html>